
###*******************************************************************************************************************###
###*** DETALLE: este Script se utiliza para iniciar la ejecución del flujo PIPELINE, en base a la PARAMETRIZACION ****###
###*** definida. Esta PARAMETRIZACION debe ser PERSONALIZADA en base a cada escenario y entorno ejecutado. ***********###
###*******************************************************************************************************************###

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dummy-pipeline-run
  namespace: dummy-tekton-appconnect
  annotations:
    image.openshift.io/pull-secret-name: ibm-entitlement-key
spec:
  params:
    - name: nombre-integration-server
      value: 'csm-microservicio'
    - name: nombre-namespace-appconnect
      value: 'dummy-tekton-appconnect'
    - name: url-repositorio-git
      value: 'https://github.com/maktup/dummy-tekton-ace.git'
    - name: nombre-subdirectorio-git
      value: 'dummy_csm_microservice'
    - name: nombre-repositorio-git
      value: 'dummy-tekton-ace'
    - name: branch-repositorio-git
      value: 'main'
    - name: nombre-proyecto-appconnect
      value: 'dummy_csm_microservice'
    - name: version-image-appconnect
      value: '12.0.7.0-r3'
    - name: licencia-image-appconnect
      value: 'L-APEH-CJUCNR'
    - name: ruta-image-appconnect
      value: 'docker.io/maktup/ibm-appconnect-12:latest'
    - name: tipo-licencia-appconnect
      value: 'CloudPakForIntegrationNonProductionFREE'
    - name: tipo-despliegue-servidor
      value: '3'

  pipelineRef:
    name: pipeline-build-and-deploy

  serviceAccountName: pipeline
  timeout: "30m"
      
  workspaces:
  - name: workspace-pipeline
    persistentVolumeClaim:
      claimName: source-pvc-pipe
