
###*******************************************************************************************************************###
###*** DETALLE: este Script se utiliza para iniciar la ejecucion del flujo PIPELINE, en base a la PARAMETRIZACION ****###
###*** definida, esta PARAMETRIZACION debe ser PERSONALIZADA en base a cada escenario y entorno ejecutado. ***********###
###*******************************************************************************************************************###

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dummy-pipeline-run
  namespace: dummy-tekton-appconnect
  annotations:
    image.openshift.io/pull-secret-name: ibm-entitlement-key
spec:
  params:
    - name: nombre-integration-server
      value: 'csm-microservicio'
    - name: nombre-namespace-appconnect
      value: 'dummy-tekton-appconnect'
    - name: url-repositorio-git
      value: 'https://github.com/maktup/dummy-tekton-ace.git'
    - name: nombre-subdirectorio-git
      value: 'dummy_csm_microservice'
    - name: nombre-repositorio-git
      value: 'dummy-tekton-ace'
    - name: branch-repositorio-git
      value: 'main'
    - name: nombre-proyecto-appconnect
      value: 'dummy_csm_microservice'
    - name: version-image-appconnect
      value: '12.0.9.0-r3'
    - name: licencia-image-appconnect
      value: 'L-SEWB-GH63KR'
    - name: ruta-image-appconnect
      value: 'docker.io/maktup/ibm-appconnect-12:latest'
    - name: tipo-licencia-appconnect
      value: 'CloudPakForIntegrationNonProduction'
    - name: tipo-despliegue-servidor
      value: '3'

  pipelineRef:
    name: pipeline-build-and-deploy

  serviceAccountName: pipeline
  timeout: "30m"
      
  workspaces:
  - name: workspace-pipeline
    persistentVolumeClaim:
      claimName: source-pvc-pipe

############################################################################################################ 
## IMPORTANTE: Otra forma es ejecutando los PARÁMETROS en base a COMANDOs del CLIENTE TEKTON como este:  
## tkn pipeline start pipeline-build-and-deploy -w name=workspace-pipeline,claimName=source-pvc-pipe -p nombre-integration-server=csm-microservicio -p nombre-namespace-appconnect=dummy-tekton-appconnect -p url-repositorio-git=https://github.com/maktup/dummy-tekton-ace.git -p nombre-subdirectorio-git=dummy_csm_microservice -p nombre-repositorio-git=dummy-tekton-ace -p branch-repositorio-git=main -p nombre-proyecto-appconnect=dummy_csm_microservice -p version-image-appconnect="12.0.9.0-r3" -p licencia-image-appconnect="L-SEWB-GH63KR" -p ruta-image-appconnect="docker.io/maktup/ibm-appconnect-12:latest" -p tipo-licencia-appconnect="CloudPakForIntegrationNonProduction" -p tipo-despliegue-servidor="3" -n dummy-tekton-appconnect
############################################################################################################   
